## Vector and matrices

In [1]:
import numpy as np

In [2]:
#Defining matrix
M = np.array([[1,2], [3,4]])

In [3]:
L = [[1,2], [3,4]]

In [4]:
L[0]

[1, 2]

In [5]:
M[0][0]

1

In [6]:
#Converting into matrix
M2 = np.matrix([[1,2], [3,4]])
M2

matrix([[1, 2],
        [3, 4]])

In [7]:
A = np.array(M2)

In [8]:
A

array([[1, 2],
       [3, 4]])

In [9]:
# Transpose the matrix
A.T

array([[1, 3],
       [2, 4]])

## Matrices to work with

In [10]:
# 1D array
Z=np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
# Multi D arrays with 0
Z=np.zeros((10,10))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
# Multi D array with 1
O = np.ones((10,10))
O

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
# Creating random N Dimension matrices
# the random number uniformaly distributed between 0 and 1
R = np.random.random((10,5))
R

array([[0.42203648, 0.46717662, 0.8047011 , 0.00363931, 0.00151219],
       [0.50686911, 0.67806689, 0.48784589, 0.29976252, 0.0443944 ],
       [0.86302215, 0.36495241, 0.87489033, 0.44744742, 0.10684706],
       [0.09846775, 0.98640954, 0.29818187, 0.57569147, 0.99704546],
       [0.57106602, 0.33117433, 0.88116828, 0.64097029, 0.48089346],
       [0.48825668, 0.73664264, 0.64787735, 0.51959249, 0.43535384],
       [0.05236166, 0.30808812, 0.92002049, 0.97665529, 0.32833354],
       [0.94409986, 0.63144355, 0.65701072, 0.29979546, 0.38498988],
       [0.95353201, 0.59617753, 0.25287316, 0.51564509, 0.85036168],
       [0.44307763, 0.61610708, 0.75553473, 0.26135554, 0.23681221]])

In [14]:
# finding the mean of value
R.mean()

0.5209246119481277

In [15]:
R.var()

0.076868708439789

## Matrix Product

In [16]:
# matrix multiplication
A = np.array([[1,2],[2,3]])

In [17]:
Ainv = np.linalg.inv(A)

In [18]:
Ainv

array([[-3.,  2.],
       [ 2., -1.]])

In [19]:
Ainv.dot(A)

array([[1., 0.],
       [0., 1.]])

In [20]:
A.dot(Ainv)

array([[1., 0.],
       [0., 1.]])

In [21]:
np.linalg.det(A)

-1.0

In [22]:
np.diag(A)

array([1, 3])

In [23]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [24]:
a = np.array([1,2])
b = np.array([3,4])

In [25]:
np.outer(a,b)

array([[3, 4],
       [6, 8]])

In [26]:
np.inner(a,b)

11

In [27]:
a.dot(b)

11

In [28]:
np.diag(A).sum()

4

In [29]:
np.trace(A)

4

In [30]:
X = np.random.randn(10,3)
X

array([[ 0.62043313,  0.24223986,  1.63935516],
       [-0.47757841,  0.11336161, -0.83899574],
       [-1.23264765,  1.40813596, -1.18975954],
       [ 0.8241637 ,  0.30408224, -0.45504315],
       [ 2.17979579,  1.51044712, -0.26161443],
       [-1.63811687,  0.59292121,  0.42193915],
       [ 0.91207842, -0.88885964,  0.56062171],
       [-0.02276868,  1.54873974, -0.24774   ],
       [-0.26533475,  1.03709337, -0.42892457],
       [ 0.35219826, -2.49394831,  1.15684315]])

In [31]:
cov = np.cov(X)

In [32]:
cov.shape

(10, 10)

## Eigen Values and Eigen Vectors

In [33]:
cov

array([[ 0.5221939 , -0.32038311, -0.76409775, -0.36121774, -0.78503963,
         0.16939854,  0.39134804, -0.55557524, -0.45124182,  1.16614008],
       [-0.32038311,  0.23113619,  0.66986151,  0.14632487,  0.36240982,
         0.12278429, -0.38627467,  0.45347774,  0.37082567, -0.9082621 ],
       [-0.76409775,  0.66986151,  2.28743976,  0.09064051,  0.45521971,
         1.07070571, -1.42276035,  1.46790529,  1.20682936, -2.82765371],
       [-0.36121774,  0.14632487,  0.09064051,  0.41385438,  0.80273358,
        -0.61096042,  0.04764704,  0.13903764,  0.10746465, -0.38674794],
       [-0.78503963,  0.36240982,  0.45521971,  0.80273358,  1.59145228,
        -1.03663225, -0.08417744,  0.44680548,  0.35424756, -1.08813851],
       [ 0.16939854,  0.12278429,  1.07070571, -0.61096042, -1.03663225,
         1.5417661 , -0.83163621,  0.55830123,  0.46990422, -0.88607795],
       [ 0.39134804, -0.38627467, -1.42276035,  0.04764704, -0.08417744,
        -0.83163621,  0.91131598, -0.89251425

In [34]:
np.linalg.eigh(cov)

(array([-9.55217082e-16, -4.03582613e-16, -1.48167590e-16, -5.20858323e-17,
         1.05427247e-16,  3.45480457e-16,  4.70206540e-16,  9.50189098e-16,
         3.35961359e+00,  9.42223857e+00]),
 array([[-0.11078853,  0.07040539,  0.06648332, -0.04555881, -0.07552407,
          0.13898143, -0.07595881, -0.92380122,  0.23867449, -0.18737577],
        [-0.77763652, -0.05277444, -0.02825999, -0.1729798 ,  0.0351689 ,
         -0.31036052, -0.48521918,  0.03833496, -0.0656956 ,  0.15163123],
        [ 0.31848571, -0.440202  ,  0.24721099, -0.11656045, -0.14775071,
          0.31014635, -0.50965186, -0.01533887,  0.12033816,  0.48744931],
        [-0.17411352,  0.17106005, -0.50201242,  0.33759466, -0.25962617,
          0.59931837, -0.17046638,  0.00836914, -0.34094642,  0.0497471 ],
        [ 0.08955834,  0.48485003,  0.51211846, -0.15238336,  0.12955777,
          0.06283029, -0.07728331, -0.12033534, -0.63728858,  0.1552123 ],
        [-0.12597151,  0.56690497,  0.09823303, -0.08341672

In [35]:
A

array([[1, 2],
       [2, 3]])

In [36]:
b

array([3, 4])

In [37]:
b = np.array([1,2])

In [38]:
b

array([1, 2])

In [39]:
x = np.linalg.inv(A).dot(b)

In [40]:
x

array([1., 0.])

In [41]:
x=np.linalg.solve(A,b)

In [42]:
x

array([1., 0.])

## Word Problem

The admission fee at a small fair is 1.50 for children and 4.00 for adults. On a certain day, 2200 people enter the fair and $5050 is collected. How many children and how many adults attended?

In [44]:
#Let x1 = no. of children, x2 = no. of adults
#x1 + x2 = 2200
#1.5x1 + 4x2 = 5050

In [45]:
A = np.array([[1,1], [1,5,4]])

In [49]:
b = np.array([2200,5050])
np.linalg.solve(A,b)

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional